build: add deno build system
catppuccin/zsh-fsh pull request #1
Opened 2024-03-10 09:18 UTC by nekowinston

I want to be able to override the colors :upside_down_face:

2024-03-10 09:54 UTC, nekowinston commented
demo: https://github.com/nekowinston/dotfiles/commit/1b6f5c775fe6473595ecdb44a88220df0e03a0e7#diff-464b654a364b5079ea0af507cb18e8c299f612f633b971258f91c1335f2e53d3R43-R52

2024-03-22 11:57 UTC, ruru-m07 requested changes
remove it 👍

2024-03-22 11:57 UTC, ruru-m07 commented on deno.json
a empty file. need to remove.

2024-03-25 08:46 UTC, nekowinston commented on deno.json
was intentional but added `{}`to make it explicit.

2024-03-25 09:00 UTC, ruru-m07 approved these changes
👍

2024-04-09 11:32 UTC, closed without merging